# Generated by Django 5.1.2 on 2024-10-26 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'verbose_name': 'پیام تیکت', 'verbose_name_plural': 'پیام\u200cهای تیکت'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد\u200cشد'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='low', max_length=128, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='section',
            field=models.CharField(choices=[('management', 'مدیریت'), ('finances', 'مالی'), ('support', 'پشتیبانی')], default='support', max_length=128, verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seen_by_admin',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seen_by_user',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال انتظار'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='pending', max_length=255, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان تیکت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر '),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد\u200cشد'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket', verbose_name='تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر '),
        ),
    ]
