# Generated by Django 5.1.2 on 2024-10-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_alter_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.customer', verbose_name='مشتری')),
                ('province', models.CharField(max_length=255, verbose_name='Province')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(max_length=255, verbose_name='House Number')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(verbose_name='Discount')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'نوع محصول', 'verbose_name_plural': 'نوع محصولات'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AddField(
            model_name='category',
            name='top_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_product', to='store.product', verbose_name='Top Product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=500, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(default='n', max_length=13, verbose_name='وضعیت نظرات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'پرداخت شده'), ('u', 'پرداخت نشده'), ('c', 'لغو شده')], default='u', max_length=255, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='نوع محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(to='store.discount', verbose_name='Discounts'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='قیمت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='محصول')),
            ],
        ),
    ]
