# Generated by Django 5.1.2 on 2024-10-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_addresses_discount_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیفات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'سفارش کالا', 'verbose_name_plural': 'سفارش کالا'},
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(max_length=255, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='house_number',
            field=models.CharField(max_length=255, verbose_name='شماره تلفن منزل'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='province',
            field=models.CharField(max_length=255, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='street',
            field=models.CharField(max_length=255, verbose_name='خیابان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='top_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_product', to='store.product', verbose_name='محصول برتر'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.FloatField(verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(to='store.discount', verbose_name='تخفیفات'),
        ),
    ]
