# Generated by Django 5.1.2 on 2024-10-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_addresses_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='top_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_product', to='store.product', verbose_name='محصول برتر'),
        ),
    ]
