# Generated by Django 5.1.2 on 2024-10-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_top_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(blank=True, null=True, to='store.discount', verbose_name='تخفیفات'),
        ),
    ]
